--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-12 18:50:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16390)
-- Name: products; Type: TABLE; Schema: public; Owner: zach
--

CREATE TABLE public.products (
    data jsonb
);


ALTER TABLE public.products OWNER TO zach;

--
-- TOC entry 4785 (class 0 OID 16390)
-- Dependencies: 217
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: zach
--

COPY public.products (data) FROM stdin;
{"key": "accelerometer_3", "type": "accelerometer", "model": "2225-10", "website": "https://www.silicondesigns.com/2225", "features": {"ft_vdc": "9 to 16", "ft_vrw": "0.007", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.18", "ft_in_run": "12", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-55", "ft_volume": "0.4", "ft_weight": "5.6", "ft_bias_it": "1", "ft_bias_tc": "50 ppm/C", "ft_g_range": "10 g", "ft_package": "PCB with Pins", "ft_frequency": "600", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "TRUE", "app_launcher": "FALSE", "app_aerospace": "TRUE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "91939619-04af-4f71-907a-49082295bc86", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.21+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "2225-10"}
{"key": "accelerometer_4", "type": "accelerometer", "model": "2225- 25", "website": "https://www.silicondesigns.com/2225", "features": {"ft_vdc": "9 to 16", "ft_vrw": "0.012", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.18", "ft_in_run": "30", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-55", "ft_volume": "0.4", "ft_weight": "5.6", "ft_bias_it": "1.5", "ft_bias_tc": "50 ppm/C", "ft_g_range": "25 g", "ft_package": "PCB with Pins", "ft_frequency": "1000", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "27d3eaf3-7eba-413a-8a16-9bd629ec7cb7", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "2225- 25"}
{"key": "accelerometer_5", "type": "accelerometer", "model": "2225-50", "website": "https://www.silicondesigns.com/2225", "features": {"ft_vdc": "9 to 16", "ft_vrw": "0.025", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.18", "ft_in_run": "60", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.4", "ft_weight": "5.6", "ft_bias_it": "3", "ft_bias_tc": "50 ppm/C", "ft_g_range": "50 g", "ft_package": "PCB with Pins", "ft_frequency": "1400", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "2f0c79a2-1d32-4617-b936-d8ccc283721f", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "2225-50"}
{"key": "accelerometer_6", "type": "accelerometer", "model": "2227-10", "website": "https://www.silicondesigns.com/2227", "features": {"ft_vdc": "9 to 16", "ft_vrw": "0.007", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.18", "ft_in_run": "12", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.132", "ft_weight": "5.6", "ft_bias_it": "1", "ft_bias_tc": "5 ppm/C", "ft_g_range": "10 g", "ft_package": "PCB with Pins", "ft_frequency": "600", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "48255aaa-b2c6-424f-a817-b4e93146dbc1", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "2227-10"}
{"key": "accelerometer_7", "type": "accelerometer", "model": "2227- 25", "website": "https://www.silicondesigns.com/2227", "features": {"ft_vdc": "9 to 16", "ft_vrw": "0.012", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.18", "ft_in_run": "30", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.132", "ft_weight": "5.6", "ft_bias_it": "1.5", "ft_bias_tc": "5 ppm/C", "ft_g_range": "25 g", "ft_package": "PCB with Pins", "ft_frequency": "1000", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "0c28e32c-890f-4d21-a88e-5ba53b333ee0", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "2227- 25"}
{"key": "accelerometer_8", "type": "accelerometer", "model": "2227-50", "website": "https://www.silicondesigns.com/2227", "features": {"ft_vdc": "9 to 16", "ft_vrw": "0.025", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.18", "ft_in_run": "60", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.132", "ft_weight": "5.6", "ft_bias_it": "3", "ft_bias_tc": "5 ppm/C", "ft_g_range": "50 g", "ft_package": "PCB with Pins", "ft_frequency": "1400", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "FALSE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "TRUE", "app_aerospace": "TRUE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "1ef466f0-5556-4f28-bcc6-42f47eefe6f4", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "2227-50"}
{"key": "accelerometer_9", "type": "accelerometer", "model": "1527J-10", "website": "https://www.silicondesigns.com/1527", "features": {"ft_vdc": "4.75  to 5.25", "ft_vrw": "0.007", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.03", "ft_in_run": "12", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.132", "ft_weight": "0.68", "ft_bias_it": "1.25", "ft_bias_tc": "25 ppm/C", "ft_g_range": "10 g", "ft_package": "LCC-20 J Lead", "ft_frequency": "420", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "cd4b395e-1879-40f3-9f9e-b8f29c0ce59b", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "1527J-10"}
{"key": "accelerometer_10", "type": "accelerometer", "model": "1527J-25", "website": "https://www.silicondesigns.com/1527", "features": {"ft_vdc": "4.75  to 5.25", "ft_vrw": "0.012", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.03", "ft_in_run": "30", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.132", "ft_weight": "0.68", "ft_bias_it": "1.5", "ft_bias_tc": "15 ppm/C", "ft_g_range": "25 g", "ft_package": "LCC-20 J Lead", "ft_frequency": "660", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "e86abb70-2615-422b-b25e-4a6ab05f08a0", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "1527J-25"}
{"key": "accelerometer_11", "type": "accelerometer", "model": "1527J-50", "website": "https://www.silicondesigns.com/1527", "features": {"ft_vdc": "4.75  to 5.25", "ft_vrw": "0.025", "ft_axis": "1", "ft_sf_it": "300", "ft_shock": "5000", "ft_watts": "0.03", "ft_in_run": "60", "ft_output": "4VDC differential", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.132", "ft_weight": "0.68", "ft_bias_it": "3", "ft_bias_tc": "15 ppm/C", "ft_g_range": "Ä… 50 g", "ft_package": "LCC-20 J Lead", "ft_frequency": "1050", "ft_interface": "analog", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Silicon Designs Inc.", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "68c8917f-0f03-4955-92f1-6c81ed972ff0", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "1527J-50"}
{"key": "accelerometer_12", "type": "accelerometer", "model": "CAS211", "website": "Gemini in-plane accelerometer | Silicon Sensing", "features": {"ft_vdc": "3.15 - 3.45", "ft_vrw": null, "ft_axis": "2", "ft_sf_it": "1000", "ft_shock": "1000", "ft_watts": "0.01", "ft_in_run": "50", "ft_output": "LSB/G", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.008", "ft_weight": "0.4", "ft_bias_it": "50", "ft_bias_tc": "200 ppm/C", "ft_g_range": "0.85 g", "ft_package": "LCC", "ft_frequency": "170", "ft_interface": "analog & SPI", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Collins/SSSL", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "11704412-f1da-45d0-9f26-0e9d9c384e62", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CAS211"}
{"key": "accelerometer_13", "type": "accelerometer", "model": "CAS212", "website": "Gemini in-plane accelerometer | Silicon Sensing", "features": {"ft_vdc": "3.15 - 3.45", "ft_vrw": null, "ft_axis": "2", "ft_sf_it": "1000", "ft_shock": "1000", "ft_watts": "0.01", "ft_in_run": "50", "ft_output": "LSB/G", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.008", "ft_weight": "0.4", "ft_bias_it": "50", "ft_bias_tc": "200 ppm/C", "ft_g_range": "2.5 g", "ft_package": "LCC", "ft_frequency": "170", "ft_interface": "analog & SPI", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Collins/SSSL", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "08e3ca17-5294-4820-b8e1-ae04bb516106", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CAS212"}
{"key": "accelerometer_14", "type": "accelerometer", "model": "CAS213", "website": "Gemini in-plane accelerometer | Silicon Sensing", "features": {"ft_vdc": "3.15 - 3.45", "ft_vrw": null, "ft_axis": "2", "ft_sf_it": "1000", "ft_shock": "1000", "ft_watts": "0.01", "ft_in_run": "50", "ft_output": "LSB/G", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.008", "ft_weight": "0.4", "ft_bias_it": "50", "ft_bias_tc": "200 ppm/C", "ft_g_range": "10 g", "ft_package": "LCC", "ft_frequency": "170", "ft_interface": "analog & SPI", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Collins/SSSL", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "921bf91e-998a-41d5-8d71-867de43cc4ea", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CAS213"}
{"key": "accelerometer_15", "type": "accelerometer", "model": "CAS214", "website": "Gemini in-plane accelerometer | Silicon Sensing", "features": {"ft_vdc": "3.15 - 3.45", "ft_vrw": null, "ft_axis": "2", "ft_sf_it": "1000", "ft_shock": "1000", "ft_watts": "0.01", "ft_in_run": "50", "ft_output": "LSB/G", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.008", "ft_weight": "0.4", "ft_bias_it": "50", "ft_bias_tc": "200 ppm/C", "ft_g_range": "30 g", "ft_package": "LCC", "ft_frequency": "170", "ft_interface": "analog & SPI", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Collins/SSSL", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "2dde1393-d500-4f30-887b-36e29a48a443", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CAS214"}
{"key": "accelerometer_16", "type": "accelerometer", "model": "CAS215", "website": "Gemini in-plane accelerometer | Silicon Sensing", "features": {"ft_vdc": "3.15 - 3.45", "ft_vrw": null, "ft_axis": "2", "ft_sf_it": "1000", "ft_shock": "1000", "ft_watts": "0.01", "ft_in_run": "50", "ft_output": "LSB/G", "ft_temp_h": "85", "ft_temp_i": "-45", "ft_volume": "0.008", "ft_weight": "0.4", "ft_bias_it": "50", "ft_bias_tc": "200 ppm/C", "ft_g_range": "96 g", "ft_package": "LCC", "ft_frequency": "170", "ft_interface": "analog & SPI", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Collins/SSSL", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "dc794af0-bbef-439d-b95b-37cf3bc8f9eb", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CAS215"}
{"key": "accelerometer_17", "type": "accelerometer", "model": "test", "website": "www.test.com", "features": {"ft_vdc": "3.3", "ft_vrw": null, "ft_axis": "1", "ft_sf_it": "10", "ft_shock": "1000", "ft_watts": "0.2", "ft_in_run": "50", "ft_output": "LSB/G", "ft_temp_h": "125", "ft_temp_i": "40", "ft_volume": "0.05", "ft_weight": "0.5", "ft_bias_it": "50", "ft_bias_tc": "200 ppm/C", "ft_g_range": "96 g", "ft_package": "LCC", "ft_frequency": "170", "ft_interface": "spi", "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": "FALSE", "app_defense": "TRUE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "DSI", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "af2d2cd8-85c6-4fb5-8ada-f75f31dfe424", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "test"}
{"key": "accelerometer_18", "type": "accelerometer", "model": "GA50", "website": "GA50", "features": {"ft_vdc": "3.3", "ft_vrw": null, "ft_axis": "1", "ft_sf_it": null, "ft_shock": "40", "ft_watts": null, "ft_in_run": null, "ft_output": null, "ft_temp_h": "85", "ft_temp_i": "-50", "ft_volume": null, "ft_weight": "0.7", "ft_bias_it": null, "ft_bias_tc": null, "ft_g_range": "5 g", "ft_package": "LCC", "ft_frequency": null, "ft_interface": null, "ft_technology": "MEMS"}, "image_url": null, "application": {"app_space": null, "app_defense": null, "app_general": null, "app_autonomy": null, "app_aviation": null, "app_launcher": null, "app_aerospace": null}, "manufacturer": "Gladiator", "source_table": "products_accelerometers", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "171fa9c9-b488-4eea-824f-e1f2ceabe493", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:45.211+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "GA50"}
{"key": "gyroscopes_1", "type": "gyroscopes", "model": "CRM100", "website": "CRM PinPoint ", "features": {"ft_arw": "0.2", "ft_axis": "1 axis", "ft_power": "0.4", "ft_volume": "3", "ft_bias_ir": "10", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "spi", "ft_standards": "NA", "ft_rate_range": "75,150, 300", "ft_technology": "mems", "ft_bias_one_hour": "250"}, "image_url": "pic url", "application": {"app_space": "TRUE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "b655007e-42b8-4681-9bb1-eefc26ec0e1e", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.82+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRM100"}
{"key": "gyroscopes_2", "type": "gyroscopes", "model": "CRM102", "website": "CRM PinPoint ", "features": {"ft_arw": "0.2", "ft_axis": "1 axis", "ft_power": "0.4", "ft_volume": "3", "ft_bias_ir": "10", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "spi", "ft_standards": "NA", "ft_rate_range": "900 - 2700", "ft_technology": "mems", "ft_bias_one_hour": "250"}, "image_url": "www.server.com/pic 1", "application": {"app_space": "TRUE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "67336c7d-f789-40f1-8310-c91db4e18046", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRM102"}
{"key": "gyroscopes_3", "type": "gyroscopes", "model": "CRM201", "website": "CRM PinPoint ", "features": {"ft_arw": "0.2", "ft_axis": "1 axis", "ft_power": "0.4", "ft_volume": "3", "ft_bias_ir": "4", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "spi", "ft_standards": "NA", "ft_rate_range": "75, 160, 300", "ft_technology": "mems", "ft_bias_one_hour": "150"}, "image_url": "www.server.com/pic 2", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "c62b0e7c-32b6-4f5e-98db-0fc0860d4240", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRM201"}
{"key": "gyroscopes_4", "type": "gyroscopes", "model": "CRM202", "website": "CRM PinPoint ", "features": {"ft_arw": "0.2", "ft_axis": "1 axis", "ft_power": "0.4", "ft_volume": "5", "ft_bias_ir": "4", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "spi", "ft_standards": "NASA", "ft_rate_range": "900-2700", "ft_technology": "mems", "ft_bias_one_hour": "150"}, "image_url": "www.server.com/pic 3", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "FALSE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "TRUE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "fb2344c9-ecc9-45b2-a1d0-0d42d244c949", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRM202"}
{"key": "gyroscopes_5", "type": "gyroscopes", "model": "G200", "website": null, "features": {"ft_arw": "0.2", "ft_axis": "1 axis", "ft_power": "0.4", "ft_volume": "4", "ft_bias_ir": "7", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "spi", "ft_standards": "NA", "ft_rate_range": "200", "ft_technology": "mems", "ft_bias_one_hour": "200"}, "image_url": "www.server.com/pic 4", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Gladiator", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "ef6b8509-dec3-472b-bc61-0601ef476a07", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "G2"}
{"key": "gyroscopes_6", "type": "gyroscopes", "model": "G300D", "website": "G300D", "features": {"ft_arw": "0.2", "ft_axis": "3 axis", "ft_power": "0.4", "ft_volume": "3", "ft_bias_ir": "6", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "spi", "ft_standards": "NA", "ft_rate_range": "250", "ft_technology": "mems", "ft_bias_one_hour": "180"}, "image_url": "www.server.com/pic 5", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Gladiator", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "a3bd50d3-9cea-4808-8ec0-c6fd43777d0a", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "G3"}
{"key": "gyroscopes_7", "type": "gyroscopes", "model": "G400", "website": null, "features": {"ft_arw": "0.2", "ft_axis": "1 axis", "ft_power": "0.4", "ft_volume": "7", "ft_bias_ir": "7", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "spi", "ft_standards": "NA", "ft_rate_range": "300", "ft_technology": "mems", "ft_bias_one_hour": "200"}, "image_url": "www.server.com/pic 6", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "Gladiator", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "f680ff5a-ff45-49b7-815f-a91d5a48f1f1", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "G4"}
{"key": "gyroscopes_8", "type": "gyroscopes", "model": "GG1320AN", "website": "GG1320an-digital-ring-laser", "features": {"ft_arw": "0.0035", "ft_axis": "1 axis", "ft_power": "1.6", "ft_volume": null, "ft_bias_ir": "0.0035", "ft_package": "Module", "ft_voltage": "5- 15", "ft_interface": "RS-422", "ft_standards": "NA", "ft_rate_range": "800", "ft_technology": "RLG", "ft_bias_one_hour": "1"}, "image_url": "www.server.com/pic 7", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "FALSE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "TRUE"}, "manufacturer": "Honeywell", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "4a84428e-5779-4312-a5a2-f3aee824f122", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "QA2000"}
{"key": "gyroscopes_9", "type": "gyroscopes", "model": "CRH03-010", "website": "CRH03", "features": {"ft_arw": "0.017", "ft_axis": "1 axis", "ft_power": "0.4", "ft_volume": "9", "ft_bias_ir": "0.04", "ft_package": "smd", "ft_voltage": "3.3", "ft_interface": "analog", "ft_standards": "NA", "ft_rate_range": "100", "ft_technology": "mems", "ft_bias_one_hour": "7"}, "image_url": "www.server.com/pic 8", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "92531cc2-ef28-4302-a390-b5165c9746e3", "country_of_origin": "USA", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRH03-010"}
{"key": "gyroscopes_10", "type": "gyroscopes", "model": "CRH03-025", "website": "CRH03", "features": {"ft_arw": "0.017", "ft_axis": "1 axis", "ft_power": "0.004", "ft_volume": "1.5", "ft_bias_ir": "0.05", "ft_package": "module", "ft_voltage": "4.85 - 5.25", "ft_interface": "analog", "ft_standards": "NA", "ft_rate_range": "25", "ft_technology": "mems", "ft_bias_one_hour": "8"}, "image_url": "www.server.com/pic 9", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "TRUE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "63fb7399-8207-4d98-a127-9254f6f5d4f0", "country_of_origin": "Japan", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRH03-025"}
{"key": "gyroscopes_11", "type": "gyroscopes", "model": "CRH03-100", "website": "CRH03", "features": {"ft_arw": "0.017", "ft_axis": "1 axis", "ft_power": "0.004", "ft_volume": "1.5", "ft_bias_ir": "0.05", "ft_package": "module", "ft_voltage": "4.85 - 5.26", "ft_interface": "analog", "ft_standards": "NA", "ft_rate_range": "100", "ft_technology": "mems", "ft_bias_one_hour": "8"}, "image_url": "www.server.com/pic 10", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "TRUE", "app_autonomy": "FALSE", "app_aviation": "FALSE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "04e2e752-ec53-4d34-a0ce-905bb5b47137", "country_of_origin": "Japan", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRH03-100"}
{"key": "gyroscopes_12", "type": "gyroscopes", "model": "CRH03-200", "website": "CRH03", "features": {"ft_arw": "0.017", "ft_axis": "1 axis", "ft_power": "0.004", "ft_volume": "1.5", "ft_bias_ir": "0.05", "ft_package": "module", "ft_voltage": "4.85 - 5.27", "ft_interface": "analog", "ft_standards": "NA", "ft_rate_range": "200", "ft_technology": "mems", "ft_bias_one_hour": "9"}, "image_url": "www.server.com/pic 11", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "FALSE", "app_autonomy": "FALSE", "app_aviation": "TRUE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "a40ac82e-b815-41ad-949d-cadf437d4e35", "country_of_origin": "Japan", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRH03-200"}
{"key": "gyroscopes_13", "type": "gyroscopes", "model": "CRH03-400", "website": "CRH03", "features": {"ft_arw": "0.017", "ft_axis": "1 axis", "ft_power": "0.004", "ft_volume": "1.5", "ft_bias_ir": "0.1", "ft_package": "module", "ft_voltage": "4.85 - 5.28", "ft_interface": "analog", "ft_standards": "DO160", "ft_rate_range": "400", "ft_technology": "mems", "ft_bias_one_hour": "9"}, "image_url": "www.server.com/pic 12", "application": {"app_space": "FALSE", "app_defense": "FALSE", "app_general": "FALSE", "app_autonomy": "FALSE", "app_aviation": "TRUE", "app_launcher": "FALSE", "app_aerospace": "FALSE"}, "manufacturer": "SSSL", "source_table": "products_gyroscopes", "_airbyte_meta": {"changes": [], "sync_id": 41084733}, "_airbyte_raw_id": "8c06ec4e-5ac4-4211-8c09-6314e1d88974", "country_of_origin": "Japan", "_airbyte_extracted_at": "2025-07-01 05:52:44.821+00", "_airbyte_generation_id": "11", "manufacturer_part_number": "CRH03-400"}
\.


-- Completed on 2025-08-12 18:50:38

--
-- PostgreSQL database dump complete
--

